/*
 Circuvia Component Definition Engine
 Developer: Vineet Sharma
 Each component defines its visual type, pins, properties and simulation metadata.
*/
const COMPONENTS = [
  // BOARDS
  {id:"arduino-uno",name:"Arduino UNO",cat:"Boards",kind:"board",pins:["D0/RX","D1/TX","D2","D3~PWM","D4","D5~PWM","D6~PWM","D7","D8","D9~PWM","D10~PWM","D11~PWM","D12","D13/LED","A0","A1","A2","A3","A4/SDA","A5/SCL","5V","3V3","GND","VIN"],props:{logic:"5V",mcu:"ATmega328P"}},
  {id:"arduino-nano",name:"Arduino Nano",cat:"Boards",kind:"board",pins:["D0/RX","D1/TX","D2","D3~PWM","D4","D5~PWM","D6~PWM","D7","D8","D9~PWM","D10~PWM","D11~PWM","D12","D13","A0","A1","A2","A3","A4/SDA","A5/SCL","5V","VIN","GND"],props:{logic:"5V"}},
  {id:"arduino-mega",name:"Arduino Mega",cat:"Boards",kind:"board",pins:["D0/RX0","D1/TX0","D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13","D14/RX3","D15/TX3","D16/RX2","D17/TX2","D18/TX1","D19/RX1","D20/SDA","D21/SCL","A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15","5V","VIN","GND"],props:{logic:"5V"}},
  {id:"esp32-devkit",name:"ESP32 DevKit",cat:"Boards",kind:"board",pins:["3V3","EN","GPIO36","GPIO39","GPIO34","GPIO35","GPIO32","GPIO33","GPIO25","GPIO26","GPIO27","GPIO14","GPIO12","GND","GPIO13","GPIO9","GPIO10","GPIO11","GPIO6","GPIO7","GPIO8","GPIO15","GPIO2","GPIO4","GPIO16","GPIO17","GPIO5","GPIO18","GPIO19","GPIO21","GPIO3/RX0","GPIO1/TX0","GPIO22","GPIO23","GND","VIN"],props:{logic:"3.3V",mcu:"ESP32"}},
  {id:"esp8266",name:"ESP8266 NodeMCU",cat:"Boards",kind:"board",pins:["A0","D0","D1","D2","D3","D4","D5","D6","D7","D8","3V3","GND","VIN"],props:{logic:"3.3V"}},

  // BASIC
  {id:"resistor",name:"Resistor",cat:"Basic",kind:"passive",pins:["A","B"],props:{value:"220Ω"}},
  {id:"potentiometer",name:"Potentiometer",cat:"Basic",kind:"passive",pins:["VCC","WIPER","GND"],props:{value:"10kΩ"}},
  {id:"capacitor",name:"Capacitor",cat:"Basic",kind:"passive",pins:["+","-"],props:{value:"100µF"}},
  {id:"diode",name:"Diode",cat:"Basic",kind:"passive",pins:["A","K"],props:{part:"1N4007"}},
  {id:"led",name:"LED",cat:"Basic",kind:"output",pins:["A","K"],props:{color:"Red"}},
  {id:"rgb-led",name:"RGB LED",cat:"Basic",kind:"output",pins:["R","G","B","COM"],props:{common:"Cathode"}},
  {id:"button",name:"Push Button",cat:"Basic",kind:"input",pins:["1","2"],props:{mode:"Momentary"}},
  {id:"switch",name:"Switch",cat:"Basic",kind:"input",pins:["COM","NO"],props:{state:"OFF"}},
  {id:"buzzer",name:"Buzzer",cat:"Basic",kind:"output",pins:["+","-"],props:{type:"Active"}},

  // TRANSISTORS
  {id:"bc547",name:"BC547 NPN",cat:"Transistors",kind:"transistor",pins:["B","C","E"],props:{package:"TO-92"}},
  {id:"bc557",name:"BC557 PNP",cat:"Transistors",kind:"transistor",pins:["B","C","E"],props:{package:"TO-92"}},
  {id:"2n2222",name:"2N2222 NPN",cat:"Transistors",kind:"transistor",pins:["B","C","E"],props:{package:"TO-92"}},
  {id:"nmosfet",name:"N-MOSFET",cat:"Transistors",kind:"transistor",pins:["G","D","S"],props:{logicLevel:"Yes"}},
  {id:"irfz44n",name:"IRFZ44N",cat:"Transistors",kind:"transistor",pins:["G","D","S"],props:{type:"Power MOSFET"}},

  // MOTORS / DRIVERS
  {id:"dc-motor",name:"DC Motor",cat:"Motors & Drivers",kind:"motor",pins:["+","-"],props:{voltage:"6V"}},
  {id:"servo",name:"Servo Motor",cat:"Motors & Drivers",kind:"motor",pins:["VCC","SIG","GND"],props:{angle:"0°"}},
  {id:"stepper",name:"Stepper Motor",cat:"Motors & Drivers",kind:"motor",pins:["A+","A-","B+","B-"],props:{type:"4-wire"}},
  {id:"l298n",name:"L298N",cat:"Motors & Drivers",kind:"driver",pins:["ENA","IN1","IN2","OUT1","OUT2","IN3","IN4","OUT3","OUT4","ENB","VS","GND","5V"],props:{channels:"2"}},
  {id:"l293d",name:"L293D",cat:"Motors & Drivers",kind:"driver",pins:["1EN","1A","1Y","2Y","2A","2EN","VCC2","GND","VCC1"],props:{channels:"2"}},
  {id:"tb6612",name:"TB6612FNG",cat:"Motors & Drivers",kind:"driver",pins:["VM","VCC","GND","AIN1","AIN2","PWMA","A01","A02","BIN1","BIN2","PWMB","B01","B02","STBY"],props:{channels:"2"}},
  {id:"uln2003",name:"ULN2003",cat:"Motors & Drivers",kind:"driver",pins:["IN1","IN2","IN3","IN4","IN5","IN6","IN7","OUT1","OUT2","OUT3","OUT4","OUT5","OUT6","OUT7","COM","GND"],props:{}},
  {id:"flyback",name:"Flyback Diode",cat:"Motors & Drivers",kind:"protection",pins:["A","K"],props:{part:"1N4007"}},

  // SENSORS
  {id:"dht11",name:"DHT11",cat:"Sensors",kind:"sensor",pins:["VCC","DATA","GND"],props:{temp:"25°C",humidity:"50%"}},
  {id:"dht22",name:"DHT22",cat:"Sensors",kind:"sensor",pins:["VCC","DATA","GND"],props:{temp:"25°C",humidity:"50%"}},
  {id:"hcsr04",name:"HC-SR04",cat:"Sensors",kind:"sensor",pins:["VCC","TRIG","ECHO","GND"],props:{distance:"100 cm"}},
  {id:"pir",name:"PIR Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","OUT","GND"],props:{motion:"None"}},
  {id:"ldr",name:"LDR Module",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{light:"50%"}},
  {id:"ir",name:"IR Obstacle Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","OUT","GND"],props:{detect:"No"}},
  {id:"flame",name:"Flame Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{level:"0%"}},
  {id:"mq2",name:"MQ-2 Gas Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","GND","AO","DO"],props:{gas:"Normal"}},
  {id:"mq135",name:"MQ-135",cat:"Sensors",kind:"sensor",pins:["VCC","GND","AO","DO"],props:{air:"Good"}},
  {id:"soil",name:"Soil Moisture",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{moisture:"50%"}},
  {id:"rain",name:"Rain Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{rain:"0%"}},
  {id:"mpu6050",name:"MPU6050",cat:"Sensors",kind:"sensor",pins:["VCC","GND","SCL","SDA","INT"],props:{i2c:"0x68"}},
  {id:"bmp280",name:"BMP280",cat:"Sensors",kind:"sensor",pins:["VIN","GND","SCL","SDA"],props:{pressure:"1013 hPa"}},
  {id:"ds18b20",name:"DS18B20",cat:"Sensors",kind:"sensor",pins:["VCC","DATA","GND"],props:{temp:"25°C"}},
  {id:"rc522",name:"RFID RC522",cat:"Sensors",kind:"module",pins:["3.3V","RST","GND","MISO","MOSI","SCK","SS","IRQ"],props:{uid:"--"}},
  {id:"joystick",name:"Joystick",cat:"Sensors",kind:"input",pins:["VCC","GND","VRX","VRY","SW"],props:{x:"0",y:"0"}},
  {id:"keypad",name:"Keypad 4x4",cat:"Sensors",kind:"input",pins:["R1","R2","R3","R4","C1","C2","C3","C4"],props:{}},

  // DISPLAYS
  {id:"lcd16",name:"16x2 LCD",cat:"Displays",kind:"display",pins:["VSS","VDD","V0","RS","RW","E","D0","D1","D2","D3","D4","D5","D6","D7","A","K"],props:{text:"Hello"}},
  {id:"i2clcd",name:"I2C LCD",cat:"Displays",kind:"display",pins:["GND","VCC","SDA","SCL"],props:{address:"0x27",text:"Hello"}},
  {id:"oled",name:"OLED 0.96",cat:"Displays",kind:"display",pins:["GND","VCC","SCL","SDA"],props:{address:"0x3C"}},
  {id:"sevenseg",name:"7 Segment",cat:"Displays",kind:"display",pins:["A","B","C","D","E","F","G","DP","COM"],props:{common:"Cathode"}},
  {id:"max7219",name:"MAX7219",cat:"Displays",kind:"display",pins:["VCC","GND","DIN","CS","CLK","DOUT"],props:{}},

  // COMMUNICATION
  {id:"hc05",name:"Bluetooth HC-05",cat:"Communication",kind:"module",pins:["VCC","GND","TXD","RXD","STATE","EN"],props:{}},
  {id:"sim800l",name:"GSM SIM800L",cat:"Communication",kind:"module",pins:["VBAT","GND","TXD","RXD","RST","DTR"],props:{}},
  {id:"neo6m",name:"GPS NEO-6M",cat:"Communication",kind:"module",pins:["VCC","GND","TX","RX","PPS"],props:{}},

  // POWER
  {id:"battery",name:"Battery",cat:"Power",kind:"power",pins:["+","-"],props:{voltage:"9V"}},
  {id:"supply5",name:"5V Supply",cat:"Power",kind:"power",pins:["VCC","GND"],props:{voltage:"5V"}},
  {id:"supply9",name:"9V Supply",cat:"Power",kind:"power",pins:["VCC","GND"],props:{voltage:"9V"}},
  {id:"supply12",name:"12V Supply",cat:"Power",kind:"power",pins:["VCC","GND"],props:{voltage:"12V"}},
  {id:"buck",name:"Buck Converter",cat:"Power",kind:"power",pins:["VIN+","VIN-","VOUT+","VOUT-"],props:{output:"5V"}},
  {id:"boost",name:"Boost Converter",cat:"Power",kind:"power",pins:["VIN+","VIN-","VOUT+","VOUT-"],props:{output:"12V"}},
  {id:"reg7805",name:"7805 Regulator",cat:"Power",kind:"regulator",pins:["IN","GND","OUT"],props:{output:"5V"}},

  {id:"breadboard",name:"Solderless Breadboard",cat:"Basic",kind:"board",pins:["+","-"],props:{size:"830 tie-points"}},
  {id:"terminal-block",name:"2-Way Terminal Block",cat:"Basic",kind:"passive",pins:["1","2"],props:{pitch:"5mm"}},
  {id:"fuse",name:"Fuse",cat:"Basic",kind:"passive",pins:["A","B"],props:{rating:"1A"}},
  {id:"inductor",name:"Inductor",cat:"Basic",kind:"passive",pins:["A","B"],props:{value:"100µH"}},
  {id:"thermistor",name:"NTC Thermistor",cat:"Basic",kind:"passive",pins:["A","B"],props:{value:"10kΩ"}},
  {id:"photoresistor",name:"Photoresistor LDR",cat:"Basic",kind:"passive",pins:["A","B"],props:{light:"50%"}},
  {id:"capacitor-ceramic",name:"Ceramic Capacitor",cat:"Basic",kind:"passive",pins:["+","-"],props:{value:"100nF"}},
  {id:"capacitor-electrolytic",name:"Electrolytic Capacitor",cat:"Basic",kind:"passive",pins:["+","-"],props:{value:"470µF"}},
  {id:"rgb-module",name:"RGB LED Module",cat:"Basic",kind:"output",pins:["R","G","B","GND"],props:{type:"Common cathode"}},
  {id:"relay",name:"5V Relay",cat:"Motors & Drivers",kind:"driver",pins:["COIL+","COIL-","COM","NO","NC"],props:{coil:"5V"}},
  {id:"relay-4ch",name:"4-Channel Relay Module",cat:"Motors & Drivers",kind:"driver",pins:["VCC","GND","IN1","IN2","IN3","IN4","COM1","NO1","COM2","NO2","COM3","NO3","COM4","NO4"],props:{channels:"4"}},
  {id:"bts7960",name:"BTS7960 Motor Driver",cat:"Motors & Drivers",kind:"driver",pins:["VCC","GND","RPWM","LPWM","R_EN","L_EN","R_IS","L_IS","B+","B-","M+","M-"],props:{voltage:"5-27V"}},
  {id:"a4988",name:"A4988 Stepper Driver",cat:"Motors & Drivers",kind:"driver",pins:["VMOT","GND","2B","2A","1A","1B","VDD","GND","1AUX","2AUX","STEP","DIR","EN","MS1","MS2","MS3","RST","SLP"],props:{microstep:"1/16"}},
  {id:"drv8825",name:"DRV8825 Stepper Driver",cat:"Motors & Drivers",kind:"driver",pins:["VMOT","GND","A1","A2","B1","B2","VDD","GND","STEP","DIR","EN","M0","M1","M2","RST","SLP"],props:{microstep:"1/32"}},
  {id:"fan",name:"DC Fan",cat:"Motors & Drivers",kind:"motor",pins:["+","-"],props:{voltage:"5V"}},
  {id:"pump",name:"Mini Water Pump",cat:"Motors & Drivers",kind:"motor",pins:["+","-"],props:{voltage:"6V"}},
  {id:"solenoid",name:"Solenoid Lock",cat:"Motors & Drivers",kind:"motor",pins:["+","-"],props:{voltage:"12V"}},
  {id:"gear-motor",name:"Gear Motor",cat:"Motors & Drivers",kind:"motor",pins:["+","-"],props:{voltage:"6V"}},
  {id:"micro-servo",name:"Micro Servo SG90",cat:"Motors & Drivers",kind:"motor",pins:["VCC","SIG","GND"],props:{angle:"0°"}},
  {id:"relay-module",name:"1-Channel Relay Module",cat:"Motors & Drivers",kind:"driver",pins:["VCC","GND","IN","COM","NO","NC"],props:{coil:"5V"}},
  {id:"pir-module",name:"HC-SR501 PIR",cat:"Sensors",kind:"sensor",pins:["VCC","OUT","GND"],props:{delay:"2s",sensitivity:"50%"}},
  {id:"sound",name:"Sound Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{sound:"Normal"}},
  {id:"vibration",name:"Vibration Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","DO","GND"],props:{detect:"No"}},
  {id:"tilt",name:"Tilt Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","OUT","GND"],props:{state:"Stable"}},
  {id:"hall",name:"Hall Effect Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","OUT","GND"],props:{magnetic:"None"}},
  {id:"ir-receiver",name:"IR Receiver VS1838B",cat:"Sensors",kind:"sensor",pins:["VCC","OUT","GND"],props:{protocol:"IR"}},
  {id:"ir-line",name:"IR Line Tracking Module",cat:"Sensors",kind:"sensor",pins:["VCC","L","R","GND"],props:{line:"White"}},
  {id:"tcrt5000",name:"TCRT5000 Line Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{surface:"White"}},
  {id:"color",name:"TCS3200 Color Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","GND","S0","S1","S2","S3","OUT"],props:{color:"None"}},
  {id:"light",name:"BH1750 Light Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","GND","SCL","SDA"],props:{lux:"300"}},
  {id:"bme280",name:"BME280",cat:"Sensors",kind:"sensor",pins:["VIN","GND","SCL","SDA"],props:{temperature:"25°C",pressure:"1013hPa"}},
  {id:"ds3231",name:"DS3231 RTC",cat:"Sensors",kind:"module",pins:["VCC","GND","SCL","SDA","SQW","32K"],props:{time:"12:00"}},
  {id:"hmc5883",name:"HMC5883L Magnetometer",cat:"Sensors",kind:"sensor",pins:["VCC","GND","SCL","SDA","DRDY"],props:{heading:"0°"}},
  {id:"adxl345",name:"ADXL345 Accelerometer",cat:"Sensors",kind:"sensor",pins:["VCC","GND","SCL","SDA","INT1","INT2"],props:{range:"±2g"}},
  {id:"mpu9250",name:"MPU9250 IMU",cat:"Sensors",kind:"sensor",pins:["VCC","GND","SCL","SDA","INT","FSYNC"],props:{interface:"I2C"}},
  {id:"max30102",name:"MAX30102 Pulse Sensor",cat:"Sensors",kind:"sensor",pins:["VIN","GND","SCL","SDA","INT"],props:{heartRate:"75BPM"}},
  {id:"mlx90614",name:"MLX90614 IR Temperature",cat:"Sensors",kind:"sensor",pins:["VIN","GND","SCL","SDA"],props:{temperature:"25°C"}},
  {id:"vl53l0x",name:"VL53L0X ToF Sensor",cat:"Sensors",kind:"sensor",pins:["VIN","GND","SCL","SDA","XSHUT"],props:{distance:"100mm"}},
  {id:"hx711",name:"HX711 Load Cell ADC",cat:"Sensors",kind:"module",pins:["VCC","GND","DT","SCK","E+","E-","A+","A-"],props:{weight:"0g"}},
  {id:"loadcell",name:"Load Cell",cat:"Sensors",kind:"sensor",pins:["E+","E-","A+","A-"],props:{capacity:"5kg"}},
  {id:"soil-cap",name:"Capacitive Soil Moisture",cat:"Sensors",kind:"sensor",pins:["VCC","AO","GND"],props:{moisture:"50%"}},
  {id:"water-level",name:"Water Level Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","SIG","GND"],props:{level:"0%"}},
  {id:"water-flow",name:"Water Flow Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","SIG","GND"],props:{flow:"0L/min"}},
  {id:"co2",name:"MH-Z19B CO2 Sensor",cat:"Sensors",kind:"module",pins:["VIN","GND","TX","RX","PWM"],props:{co2:"400ppm"}},
  {id:"mq3",name:"MQ-3 Alcohol Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","GND","AO","DO"],props:{level:"Normal"}},
  {id:"mq7",name:"MQ-7 CO Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","GND","AO","DO"],props:{level:"Normal"}},
  {id:"flame-module",name:"IR Flame Module",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{level:"0%"}},
  {id:"rain-module",name:"Rain Detection Module",cat:"Sensors",kind:"sensor",pins:["VCC","AO","DO","GND"],props:{level:"0%"}},
  {id:"capacitive-touch",name:"TTP223 Touch Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","SIG","GND"],props:{touch:"Off"}},
  {id:"vcc-module",name:"Voltage Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","S","GND"],props:{voltage:"0V"}},
  {id:"current-sensor",name:"ACS712 Current Sensor",cat:"Sensors",kind:"sensor",pins:["VCC","OUT","GND"],props:{current:"0A"}},
  {id:"ina219",name:"INA219 Current/Voltage",cat:"Sensors",kind:"sensor",pins:["VIN+","VIN-","VCC","GND","SCL","SDA"],props:{current:"0A"}},
  {id:"raspberry-pi-pico",name:"Raspberry Pi Pico",cat:"Boards",kind:"board",pins:["VSYS","GND","GP0","GP1","GP2","GP3","GP4","GP5","GP6","GP7","GP8","GP9","GP10","GP11","GP12","GP13","GP14","GP15","GP16","GP17","GP18","GP19","GP20","GP21","GP22","RUN","3V3","ADC0","ADC1","ADC2","ADC3"],props:{logic:"3.3V"}},
  {id:"arduino-promini",name:"Arduino Pro Mini",cat:"Boards",kind:"board",pins:["D0/RX","D1/TX","D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13","A0","A1","A2","A3","A4","A5","VCC","RAW","GND"],props:{logic:"5V"}},
  {id:"arduino-leonardo",name:"Arduino Leonardo",cat:"Boards",kind:"board",pins:["D0/RX","D1/TX","D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13","A0","A1","A2","A3","A4","A5","A6","5V","VIN","GND"],props:{logic:"5V"}},
  {id:"esp32-s3",name:"ESP32-S3 Dev Board",cat:"Boards",kind:"board",pins:["3V3","EN","IO1","IO2","IO3","IO4","IO5","IO6","IO7","IO8","IO9","IO10","IO11","IO12","IO13","IO14","IO15","IO16","IO17","IO18","IO19","IO20","IO21","IO35","IO36","IO37","IO38","IO39","IO40","GND","VIN"],props:{logic:"3.3V"}},
  {id:"stm32-bluepill",name:"STM32 Blue Pill",cat:"Boards",kind:"board",pins:["3V3","GND","A0","A1","A2","A3","A4","A5","A6","A7","B0","B1","B6","B7","B8","B9","C13","C14","C15","5V"],props:{logic:"3.3V"}},
  {id:"attiny85",name:"ATtiny85",cat:"Boards",kind:"board",pins:["VCC","PB0","PB1","PB2","PB3","PB4","GND"],props:{logic:"5V"}},
  {id:"microbit",name:"micro:bit",cat:"Boards",kind:"board",pins:["3V","GND","P0","P1","P2","P3","P4","P5","P6","P7","P8","P9","P10","P11","P12","P13","P14","P15","P16","P19","P20"],props:{logic:"3.3V"}},
  {id:"relay-board-8",name:"8-Channel Relay Board",cat:"Motors & Drivers",kind:"driver",pins:["VCC","GND","IN1","IN2","IN3","IN4","IN5","IN6","IN7","IN8"],props:{channels:"8"}},
  {id:"mosfet-module",name:"MOSFET Trigger Module",cat:"Motors & Drivers",kind:"driver",pins:["VCC","GND","SIG","VIN+","VIN-","OUT+","OUT-"],props:{type:"N-MOSFET"}},
  {id:"logic-level",name:"4-Channel Logic Level Converter",cat:"Communication",kind:"module",pins:["HV","LV","GND","HV1","HV2","HV3","HV4","LV1","LV2","LV3","LV4"],props:{channels:"4"}},
  {id:"hc12",name:"HC-12 Wireless Module",cat:"Communication",kind:"module",pins:["VCC","GND","TXD","RXD","SET"],props:{frequency:"433MHz"}},
  {id:"lora",name:"LoRa SX1278",cat:"Communication",kind:"module",pins:["VCC","GND","MISO","MOSI","SCK","NSS","RST","DIO0"],props:{frequency:"433MHz"}},
  {id:"nrf24",name:"nRF24L01",cat:"Communication",kind:"module",pins:["VCC","GND","CE","CSN","SCK","MOSI","MISO","IRQ"],props:{frequency:"2.4GHz"}},
  {id:"ethernet",name:"W5500 Ethernet Module",cat:"Communication",kind:"module",pins:["VCC","GND","SCK","MOSI","MISO","CS","RST","INT"],props:{interface:"SPI"}},
  {id:"microsd",name:"MicroSD Card Module",cat:"Communication",kind:"module",pins:["VCC","GND","CS","MOSI","MISO","SCK"],props:{interface:"SPI"}},
  {id:"rs485",name:"MAX485 Module",cat:"Communication",kind:"module",pins:["VCC","GND","DI","RO","DE","RE","A","B"],props:{interface:"RS485"}},
  {id:"can",name:"MCP2515 CAN Module",cat:"Communication",kind:"module",pins:["VCC","GND","CS","SO","SI","SCK","INT","CANH","CANL"],props:{interface:"CAN"}},
  {id:"usb-ttl",name:"USB-TTL Adapter",cat:"Communication",kind:"module",pins:["5V","3V3","GND","TX","RX"],props:{logic:"5V/3.3V"}},
  {id:"keypad4",name:"4x4 Matrix Keypad",cat:"Input",kind:"input",pins:["R1","R2","R3","R4","C1","C2","C3","C4"],props:{keys:"16"}},
  {id:"rotary",name:"Rotary Encoder",cat:"Input",kind:"input",pins:["VCC","GND","CLK","DT","SW"],props:{type:"Incremental"}},
  {id:"ir-remote",name:"IR Remote",cat:"Input",kind:"input",pins:["SIG"],props:{protocol:"NEC"}},
  {id:"joystick-module",name:"2-Axis Joystick Module",cat:"Input",kind:"input",pins:["VCC","GND","VRX","VRY","SW"],props:{range:"0-1023"}},
  {id:"reed",name:"Reed Switch",cat:"Input",kind:"input",pins:["1","2"],props:{state:"Open"}},
  {id:"mic",name:"Electret Microphone Module",cat:"Input",kind:"input",pins:["VCC","AO","DO","GND"],props:{gain:"Auto"}},
  {id:"matrix8",name:"8x8 LED Matrix",cat:"Displays",kind:"display",pins:["VCC","GND","DIN","CS","CLK"],props:{driver:"MAX7219"}},
  {id:"tm1637",name:"TM1637 4-Digit Display",cat:"Displays",kind:"display",pins:["VCC","GND","DIO","CLK"],props:{digits:"4"}},
  {id:"oled128",name:"OLED 1.3 inch",cat:"Displays",kind:"display",pins:["VCC","GND","SCL","SDA"],props:{resolution:"128x64"}},
  {id:"eink",name:"E-Ink Display",cat:"Displays",kind:"display",pins:["VCC","GND","SCK","MOSI","CS","DC","RST","BUSY"],props:{resolution:"2.13in"}},
  {id:"neopixel",name:"NeoPixel Ring",cat:"Displays",kind:"output",pins:["VCC","DIN","DOUT","GND"],props:{pixels:"16"}},
  {id:"led-strip",name:"WS2812 LED Strip",cat:"Displays",kind:"output",pins:["VCC","DIN","GND"],props:{pixels:"30"}},
  {id:"relay-indicator",name:"Relay Indicator Module",cat:"Output",kind:"output",pins:["VCC","IN","GND"],props:{state:"OFF"}},
  {id:"rgb-strip",name:"RGB LED Strip",cat:"Displays",kind:"output",pins:["VCC","R","G","B"],props:{voltage:"12V"}},
  {id:"speaker",name:"8Ω Speaker",cat:"Output",kind:"output",pins:["+","-"],props:{impedance:"8Ω"}},
  {id:"motorized-pump",name:"Mini Pump Module",cat:"Output",kind:"motor",pins:["+","-"],props:{voltage:"5V"}},
  {id:"solenoid-valve",name:"Solenoid Valve",cat:"Output",kind:"motor",pins:["+","-"],props:{voltage:"12V"}},
  {id:"power-supply",name:"DC Bench Supply",cat:"Power",kind:"power",pins:["+5V","+12V","GND"],props:{output:"5V/12V"}},
  {id:"coin-cell",name:"CR2032 Battery",cat:"Power",kind:"power",pins:["+","-"],props:{voltage:"3V"}},
  {id:"aa-pack",name:"AA Battery Pack",cat:"Power",kind:"power",pins:["+","-"],props:{voltage:"6V"}},
  {id:"usb-power",name:"USB 5V Power",cat:"Power",kind:"power",pins:["5V","GND"],props:{voltage:"5V"}},
  {id:"power-module",name:"Breadboard Power Module",cat:"Power",kind:"power",pins:["IN+","IN-","OUT+","OUT-"],props:{output:"5V/3.3V"}},
  {id:"lm2596",name:"LM2596 Buck Converter",cat:"Power",kind:"regulator",pins:["IN+","IN-","OUT+","OUT-"],props:{output:"Adjustable"}},
  {id:"ams1117",name:"AMS1117 Regulator",cat:"Power",kind:"regulator",pins:["VIN","GND","VOUT"],props:{output:"3.3V"}},
  {id:"logic-and",name:"74HC08 AND Gate",cat:"Logic ICs",kind:"ic",pins:["VCC","GND","A1","B1","Y1","A2","B2","Y2","A3","B3","Y3","A4","B4","Y4"],props:{logic:"AND"}},
  {id:"logic-or",name:"74HC32 OR Gate",cat:"Logic ICs",kind:"ic",pins:["VCC","GND","A1","B1","Y1","A2","B2","Y2","A3","B3","Y3","A4","B4","Y4"],props:{logic:"OR"}},
  {id:"logic-not",name:"74HC04 NOT Gate",cat:"Logic ICs",kind:"ic",pins:["VCC","GND","A1","Y1","A2","Y2","A3","Y3","A4","Y4","A5","Y5","A6","Y6"],props:{logic:"NOT"}},
  {id:"logic-nand",name:"74HC00 NAND Gate",cat:"Logic ICs",kind:"ic",pins:["VCC","GND","A1","B1","Y1","A2","B2","Y2","A3","B3","Y3","A4","B4","Y4"],props:{logic:"NAND"}},
  {id:"logic-nor",name:"74HC02 NOR Gate",cat:"Logic ICs",kind:"ic",pins:["VCC","GND","A1","B1","Y1","A2","B2","Y2","A3","B3","Y3","A4","B4","Y4"],props:{logic:"NOR"}},
  {id:"logic-xor",name:"74HC86 XOR Gate",cat:"Logic ICs",kind:"ic",pins:["VCC","GND","A1","B1","Y1","A2","B2","Y2","A3","B3","Y3","A4","B4","Y4"],props:{logic:"XOR"}},
  {id:"shift-register",name:"74HC595 Shift Register",cat:"Logic ICs",kind:"ic",pins:["VCC","GND","SER","SRCLK","RCLK","OE","SRCLR","QA","QB","QC","QD","QE","QF","QG","QH"],props:{bits:"8"}},
  {id:"timer555",name:"NE555 Timer",cat:"Logic ICs",kind:"ic",pins:["GND","TRIG","OUT","RESET","CTRL","THRESH","DISCH","VCC"],props:{mode:"Timer"}},
  {id:"opamp",name:"LM358 Op-Amp",cat:"Logic ICs",kind:"ic",pins:["VCC","OUT1","IN1-","IN1+","GND","IN2+","IN2-","OUT2"],props:{channels:"2"}},
  {id:"diode-bridge",name:"Bridge Rectifier",cat:"Power",kind:"power",pins:["AC1","AC2","+","-"],props:{rating:"2A"}},
  {id:"crystal16",name:"16MHz Crystal",cat:"Basic",kind:"passive",pins:["X1","X2"],props:{frequency:"16MHz"}},
  {id:"pot-module",name:"Potentiometer Module",cat:"Input",kind:"input",pins:["VCC","AO","GND"],props:{value:"10kΩ"}},
  {id:"button-module",name:"Push Button Module",cat:"Input",kind:"input",pins:["VCC","OUT","GND"],props:{mode:"Momentary"}}
];

const componentById = Object.fromEntries(COMPONENTS.map(c=>[c.id,c]));
